### ISSUE TITLE
C版本第一行的数字是什么

### ISSUE THREAD

**Issue by TryA9ain** [Gality369/CS-Loader#2]
![image](https://user-images.githubusercontent.com/51145610/90970043-7149aa00-e532-11ea-9a92-82fb9d411823.png)
![image](https://user-images.githubusercontent.com/51145610/90970058-91796900-e532-11ea-83ee-6e4f73aa731e.png)

**Comment by Gality369** [comment]
应该可以了,您再重新试试,这里原本是generator中生成加密payload时第一步base64后的字符串长度,之前忘记输出了

**Comment by handbye** [comment]
@TryA9ain 你好，请问你配置完毕后可以上线吗
